<?php
class OutMessage{
	const TYPE_ATUH_DIALOGUE="ATUH_DIALOGUE";
	const TYPE_ATUH_NO_REQUEST="ATUH_NO_REQUEST";
	const TYPE_ATUH_RESPONSE_TIMEOUT="ATUH_RESPONSE_TIMEOUT";
	const TYPE_ATUH_UNKNOWN="ATUH_UNKNOWN";
	var routing_key;
	var body;	
}
?>
